---
title: "Appendix"
author: "Max Aantjes"
date: "26/08/2020"
output:
  github_document:
    toc: true
    toc_depth: 2
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(openxlsx)
library(dplyr)
```


```{r}
replace_special_char <- function(x) {
        original <- c("á", "é", "ó", "ú", "ñ", "í")
        new <- c("a", "e", "o", "u", "n", "i")
        for(i in 1:length(original)) {
                x <- gsub(original[i], new[i], x)}
        return(x)}

df <- read.xlsx("Registros-Administrativos-2019-2020-Inicio.xlsx", sheet = "Registros Administrativos", startRow = 13)

names(df) <- tolower(replace_special_char(names(df)))
names(df)[2] <- "duplicate"
names(df)[34] <- "tot.students"

df <- df %>%
        select(-duplicate) %>%
        mutate(canton = factor(canton))  %>%
        mutate(sostenimiento = factor(sostenimiento, levels = c("Fiscal", "Fiscomisional", "Particular", "Municipal"), labels = c("public", "mixed", "private", "public"))) %>%
        filter(tot.students != 0)
```

```{r}
df1 <- df %>%
        mutate(class.size = tot.students/total.docentes) 

p <- ggplot(data = df1, aes(x = class.size, y = sostenimiento))
p1 <- p + geom_boxplot() + xlim(0, 50) + facet_grid(~zona.inec)
p1
```


```{r}
df1 <- df %>%
        group_by(canton, sostenimiento) %>%
        summarise(n = sum(tot.students)) %>%
        pivot_wider(names_from = sostenimiento, values_from = n) %>%
        mutate(public = ifelse(is.na(public), 0, public)) %>%
        mutate(mixed = ifelse(is.na(mixed), 0, mixed)) %>%
        mutate(private = ifelse(is.na(private), 0, private)) %>%
        mutate(total = public + mixed + private) %>%
        mutate(public.percent = public/total) %>%
        mutate(mixed.percent = mixed/total) %>%
        mutate(private_percent = private/total)

df2 <- df1 %>%
        arrange(-private_percent) %>%
        mutate(private_percent = private_percent * 100) %>%
        select(canton, private_percent, total)

head(df2, 10)
```

```{r}
df1 <- df %>%
        group_by(zona, sostenimiento) %>%
        summarise(n = sum(tot.students)) %>%
        pivot_wider(names_from = sostenimiento, values_from = n) %>%
        mutate(public = ifelse(is.na(public), 0, public)) %>%
        mutate(mixed = ifelse(is.na(mixed), 0, mixed)) %>%
        mutate(private = ifelse(is.na(private), 0, private)) %>%
        mutate(total = public + mixed + private) %>%
        mutate(public.percent = public/total) %>%
        mutate(mixed.percent = mixed/total) %>%
        mutate(private_percent = private/total)

df2 <- df1 %>%
        arrange(-private_percent) %>%
        mutate(private_percent = private_percent * 100) %>%
        select(canton, private_percent, total)

head(df2, 10)   
```

```{r}
df1 <- df %>%
        group_by(sostenimiento) %>%
        summarise(no.teachers = sum(total.docentes))
df1
```

```{r}
df1 <- df %>%
        group_by(sostenimiento) %>%
        count()
df1
```

```{r}
y2009s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=10555"
y2010s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=10557"
y2011s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=10559"
y2012s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=10561"
y2013s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=12176"
y2014s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=10567"
y2015s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=10569"
y2016s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=10573"
y2017s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=12645"
y2018s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=15711"
y2019s <- "https://educacion.gob.ec/wp-content/plugins/download-monitor/download.php?id=15713"

links1 <- list(y2009s, y2010s, y2011s, y2012s, y2013s, 
               y2014s, y2015s, y2016s, y2017s)
links2 <- list(y2018s, y2019s)
 
load.xlsx <- function(x, y, z){
        y <- read.xlsx(x, sheet = y, startRow = z)
        return(y)}

listA <- lapply(links1, load.xlsx, y = 1, z = 11)
dfA <- do.call(rbind, listA)
names(dfA) <- replace_special_char(names(dfA))
dfA1 <- dfA %>%
        select(Periodo, Total.Estudiantes, Total.Docentes, 
               Nombre.Institucion, Zona.Inec, Sostenimiento)

names(dfB) <- replace_special_char(names(dfB))
dfB1 <- dfB %>%
        select(Periodo, Total.Estudiantes, Total.Docentes, 
               Nombre.Institucion, Zona.Inec, Sostenimiento)

names(dfC) <- replace_special_char(names(dfC))
names(dfC)[2] <- "duplicate"
dfC1 <- dfC %>%
        select(-duplicate) %>%
        select(Periodo, "Total.Estudiantes" = 'Total.estudiantes.(Inicial.a.3ro..De.Bachillerato)', 
               Total.Docentes, Nombre.Institucion, Zona.Inec, Sostenimiento)

df <- rbind(dfA1, dfB1, dfC1)

df1 <- df %>%
        select("year" = Periodo, "tot.students" = Total.Estudiantes, 
               "tot.teachers" = Total.Docentes, Sostenimiento, "name" = Nombre.Institucion,
               "area" = Zona.Inec) %>%
        mutate(year = str_extract(year, "^[0-9]{4}"))  %>%
        mutate(year = as.Date(paste0(year, "-01-01"))) %>%
        mutate(finance.source= factor(Sostenimiento, levels = c("Fiscal", "Fiscomisional", 
                                                                "Particular", "Municipal",
                                                                "Particular Laico",
                                                                "Particular Religioso"), 
                                      labels = c("public", "mixed", "private", "public",
                                                 rep("private", 2)))) %>%
        filter(tot.students != 0 & tot.teachers != 0)

dfCS <- df1 %>%
        filter(finance.source == "public" &
                 area == "UrbanaINEC") %>%
        mutate(class.size = tot.students/tot.teachers) %>%
        group_by(year) %>%
        summarise(class.size = median(class.size))

dfPP <- df1 %>%
        filter(area == "UrbanaINEC") %>%
        group_by(year, finance.source) %>%
        summarise(n = sum(tot.students)) %>%
        pivot_wider(names_from = finance.source, values_from = n) %>%
        mutate(prop = private/sum(public, mixed, private))

## Proportion of Students enrolled in Private Education
qplot(y = dfPP$prop, x = dfPP$year)

## Number of Students per Teacher at Median Public School
qplot(y = dfCS$class.size, x = dfCS$year)
qplot(dfPP$prop, dfCS$class.size)


dfB <- read.xlsx(y2018s, sheet = 2, startRow = 13)
dfC <- read.xlsx(y2019s,  sheet = "Registros Administrativos", startRow = 13)
rbind(dfA, dfB, dfC)



```

```{r}
name_check <- function(x, y){
  for(i in 1:length(names(x))){
    if(isFALSE(identical(names(x)[i], names(y)[i]))){
      sapply(c(i, names(x)[i], names(y)[i]), print)}}
  message("all other colnames identical")}
```

```{r}
## Sources
"https://blogs.iadb.org/educacion/es/covid-19-y-la-transicion-de-la-educacion-privada-a-la-publica-en-ecuador/"
"https://www.elnuevosiglo.com.co/articulos/07-2020-la-transicion-de-la-educacion-privada-la-publica"
"https://www.infobae.com/america/mexico/2020/08/04/la-sep-esta-lista-para-migracion-de-alumnos-de-escuelas-privadas-a-publicas/"
"https://www.infobae.com/america/mexico/2020/08/04/la-sep-esta-lista-para-migracion-de-alumnos-de-escuelas-privadas-a-publicas/"
"https://www.24-horas.mx/2020/08/24/educacion-en-tiempos-de-covid-crece-migracion-de-escuelas-privadas-a-publicas/"
"https://www.eldiariodechihuahua.mx/local/temen-migracion-de-escuelas-privadas-a-publicas-20200805-1692951.html"
"https://www.milenio.com/politica/sep-lista-migracion-alumnos-escuelas-privadas-publicas"
"https://politica.expansion.mx/mexico/2020/08/10/el-covid-19-pone-en-riesgo-a-1-de-cada-4-escuelas-privadas"
"https://www.elfinanciero.com.mx/empresas/advierten-que-4-de-cada-10-de-escuelas-privadas-cerraran-por-educacion-a-distancia"
```

